on:
  workflow_dispatch:
  push:

permissions:
  id-token: write

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: clone source code
      uses: actions/checkout@v4    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::034851978623:role/github-terraform-integration
        aws-region: us-east-1
    - name: terraform init cli
      run: terraform init
    - name: terraform plan cli
      run: terraform plan
    - name: terraform deploy cli
      run: terraform apply -auto-approve      